#pragma checksum "..\..\..\UI\MyTaskPane1.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "EC0D1722E0A52360DA20512F4EBC8F21EE72FE9DA2CF513E3D63233AB80792A2"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using SmartDetection.UI;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SmartDetection.UI {
    
    
    /// <summary>
    /// MyTaskPane1
    /// </summary>
    public partial class MyTaskPane1 : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\UI\MyTaskPane1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl tabControl;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\UI\MyTaskPane1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabBridge;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\UI\MyTaskPane1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker datePickerCtl;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\UI\MyTaskPane1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sGroupBox;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\UI\MyTaskPane1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sLineBox;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\..\UI\MyTaskPane1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sUpdownBox;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\..\UI\MyTaskPane1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid StationData;
        
        #line default
        #line hidden
        
        
        #line 258 "..\..\..\UI\MyTaskPane1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabResult;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SmartDetection;component/ui/mytaskpane1.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\UI\MyTaskPane1.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.tabControl = ((System.Windows.Controls.TabControl)(target));
            
            #line 15 "..\..\..\UI\MyTaskPane1.xaml"
            this.tabControl.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.TabSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TabBridge = ((System.Windows.Controls.TabItem)(target));
            return;
            case 3:
            this.datePickerCtl = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 4:
            this.sGroupBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.sLineBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.sUpdownBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            
            #line 130 "..\..\..\UI\MyTaskPane1.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.queryPlan);
            
            #line default
            #line hidden
            return;
            case 8:
            this.StationData = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 9:
            this.TabResult = ((System.Windows.Controls.TabItem)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

